FROM python:3.9-slim

WORKDIR /app
COPY app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

ENV WELCOME_HEADER="Welcome to the custom app"
ENV PORT=5000
ENV LOG_LEVEL="INFO"

CMD ["python", "app.py"]